# (c) 2025 by CoreWeave, Inc.
#
# This file is part of Slurm Containers.
#
# Slurm Containers is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# Slurm Containers is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with Slurm Containers; if not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA

name: "Build Slurm Images for SUNK"
description: "Composite workflow that builds Slurm images for SUNK."
inputs:
  context:
    description: "A directory containing a Dockerfile which buildx will use to build your image."
    required: true
    default: ""
  image-name:
    description: "The target image name."
    required: true
    default: ""
  image-tag-suffix:
    description: "Suffix to append to the image tag."
    required: false
    default: ""
  dockerfile:
    description: "Filepath resolving to the Dockerfile to use."
    required: true
    default: ""
  doppler-token:
    description: "The Doppler token to fetch the BuildKit client certs (e.g. secrets.ORG_BUILDKIT_CLIENT_TOKEN)."
    required: true
    default: ""
  buildx-args:
    description: "Extra arguments to pass to the `buildx build` command."
    required: false
    default: ""
  cloudsmith-repo-name:
    description: "The name of the Cloudsmith repository to use."
    required: true
    default: ""
  cloudsmith-service:
    description: "The name of the Cloudsmith service account to use."
    required: true
    default: ""
  github-token:
    description: "The GitHub token to use for authentication."
    required: true
    default: ""

outputs:
  image_name_with_tag:
    description: "The full image name."
    value: ${{ steps.assemble-image-name.outputs.image_name }}:${{ steps.determine-tag.outputs.tag }}
  image_name:
    description: "The image name not including the tag."
    value: ${{ steps.assemble-image-name.outputs.image_name }}
  image_tag:
    description: "The computed image tag."
    value: ${{ steps.determine-tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Build Registry Auth
      id: build-registry-auth
      uses: ./.github/actions/images/build-docker-config
      with:
        cloudsmith-service: ${{ inputs.cloudsmith-service }}
        github-token: ${{ inputs.github-token }}

    - name: Determine image tag
      id: determine-tag
      uses: ./.github/actions/images/determine-tag
      with:
        tag-suffix: ${{ inputs.image-tag-suffix }}

    - name: Assemble image name
      id: assemble-image-name
      shell: bash
      run: |
        echo "image_name=${{ env.CI_REGISTRY }}/coreweave/${{ inputs.cloudsmith-repo-name }}/${{ inputs.image-name }}" >> $GITHUB_OUTPUT
        echo "output_image_name=${{ env.OUTPUT_CI_REGISTRY }}/${{ inputs.image-name }}" >> $GITHUB_OUTPUT

    - name: Compute hash of image name
      id: compute-image-name-hash
      shell: bash
      run: |
        echo "hash=$(echo -n ${{ steps.assemble-image-name.outputs.image_name }} | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

    - name: Debug
      if: runner.debug == '1'
      shell: bash
      run: |
        echo "::group::Build Image inputs"
          echo "context=${{ inputs.context }}"
          echo "dockerfile=${{ inputs.dockerfile }}"
          echo "inputs.cloudsmith-repo-name=${{ inputs.cloudsmith-repo-name }}"
          echo "image-name=${{ inputs.image-name }}"
          echo "image-tag-suffix=${{ inputs.image-tag-suffix }}"
          echo "buildx-args=${{ inputs.buildx-args }}"
          echo "cache_image=${{ env.CI_CACHE_IMAGE }}"
        echo "::endgroup::"

        echo "::group::Step outputs"
          echo "tag=${{ steps.determine-tag.outputs.tag }}"
          echo "image_name=${{ steps.assemble-image-name.outputs.image_name }}"
          echo "hash=${{ steps.compute-image-name-hash.outputs.hash }}"
        echo "::endgroup::"

    - name: Build image
      id: build-image
      uses: coreweave/actions-public/build/buildx-build@v1.0.0
      with:
        context: ${{ inputs.context }}
        tags: ${{ steps.assemble-image-name.outputs.image_name }}:${{ steps.determine-tag.outputs.tag }}
        dockerfile: ${{ inputs.dockerfile }}
        endpoint: tcp://buildkitd-amd64.git-devprod:1234
        append: |
          - endpoint: tcp://buildkitd-arm64.git-devprod:1234
        doppler-token: ${{ inputs.doppler-token }}
        doppler-config: prod
        doppler-project: devprod-buildkit-consumer
        docker-config: ${{ steps.build-registry-auth.outputs.docker_config_json_filename }}
        # Using suggested cache compression options from https://github.com/moby/buildkit#registry-push-image-and-cache-separately
        buildx-args: |
          --platform=linux/amd64,linux/arm64
          ${{ inputs.buildx-args }}
          --cache-from=type=registry,ref=${{ env.CI_CACHE_IMAGE }}:${{ steps.compute-image-name-hash.outputs.hash }}
          --cache-to=type=registry,image-manifest=true,mode=max,compression=zstd,compression-level=1,ignore-error=true,ref=${{ env.CI_CACHE_IMAGE }}:${{ steps.compute-image-name-hash.outputs.hash }}

    - name: Output image name
      id: output-image-name
      shell: bash
      run: echo "::notice::${{ steps.assemble-image-name.outputs.output_image_name }}:${{ steps.determine-tag.outputs.tag }}"
