# SPDX-FileCopyrightText: © 2025 CoreWeave, Inc. <sunk@coreweave.com>

branches:
  - main
preset: "conventionalcommits"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - semantic-release-gha-output
repositoryUrl: "https://github.com/coreweave/slurm-containers.git"
