# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-PackageName: slurm-containers
umask u=rwx,g=rwx,o=
ulimit -n 16384

source /etc/profile.d/bash_completion.sh
source /etc/profile.d/slurm_completion.sh

alias dl='sinfo -t "drain&idle" -NO "NodeList:45,Comment:10,Timestamp:25,Reason:130" | uniq'
alias dld='sinfo -t drain -NO "NodeList:45,Comment:10,Timestamp:25,Reason:130" | uniq'
alias downl='sinfo -t "down" -NO "NodeList:45,Comment:10,Timestamp:25,Reason:130" | uniq'
alias sn='scontrol show node'
alias reboot='/usr/share/sunk/bin/reboot.sh'
alias undrain-prolog='scontrol show nodes --json | jq -r ".nodes[] | select(.reason == \"prolog pre-hook failed (sunk:verify-undrain)\") | .name" | xargs -I % sh -c "echo Undraining %; scontrol update nodename=% state=resume"'

function undrain() {
  if [ "$#" -ne 1 ]
  then
          echo "Usage: undrain <node>"
          return 1
  fi
  scontrol update nodename=$1 state=resume
}

function drain() {
  if [ "$#" -ne 2 ]
  then
          echo "Usage: drain <node> <reason>"
          return 1
  fi
  scontrol update nodename=$1 state=drain reason="$(whoami): $2"
}
