# SPDX-FileCopyrightText: 2025 CoreWeave, Inc.
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-PackageName: slurm-containers

name: Release Orchestrator
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*coreweave.[0-9]+"

permissions:
  contents: read
  packages: read # Required for pulling the cw actions images

jobs:
  build-images:
    uses: ./.github/workflows/build-images.yaml
    with:
      registry-path: ""
      version-tag: ${{ github.ref_name }}
    secrets: inherit
    permissions:
      contents: read # required for accessing the repo contents
      id-token: write # required for requesting JWT and OIDC tokens
      packages: write # Required for pushing images to GHCR
